#!/usr/bin/env python3

# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

sum = 0

a = 0
b = 1

def gen_fb(a, b):
  c = a + b
  a = b
  b = c
  return a, b

while True:
  a, b = gen_fb(a, b)
  if (b < 4000000):
    if (b % 2 == 0):
      print(str(b) + " and sum:", end = ' ')
      sum += b
      print(str(sum))
    else:
      print(str(b))
  else:
    break



