#!/usr/bin/env python3

#  Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#  It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#  Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

pen = []
for i in range(1, 10000):
  pen.append(int(i*(3*i-1)/2))

#  print(pen)
rec = 0

for i in range(1, 10000):
  if (i % 100 == 0):
    print("checked " + str(i))
  for j in range(i):
    s = pen[i] + pen[j]
    #  print(s)
    d = pen[i] - pen[j]
    #  print(d)
    if (s in pen) and (d in pen):
      print("good pair " + str(pen[i]) + " and " + str(pen[j]) + " with sum " \
          + str(s) + " and dif " + str(d))
      if (rec == 0):
        rec = d
      if d < rec:
        rec = d
        print(">> new record <<")
      else:
        print("")

print("record " + str(rec))
